#
#  ZZZZZ  CCCCC  EEEEEEE                 iii  fffff
#     ZZ CC    C EE       gggggg  gggggg     ff    yy   yy
#    ZZ  CC      EEEEE   gg   gg gg   gg iii fffff  yy   yy
#   ZZ   CC    C EE      ggggggg ggggggg iii ff     yyyyyy
#  ZZZZZ  CCCCC  EEEEEEE      gg      gg iii ff         yy
#                         ggggg   ggggg             yyyyy
#  Project: ZCEggify
#  Authors: Zandercraft, WiseHollow
#  Current Maintainer: Zandercraft
#  Website: https://github.com/Zandercraft/ZCEggify
#

# What projectile catches the creature.
Projectile Catcher: STICK
# Cost Mode: [ NONE, ITEM, VAULT ]
Cost Mode: ITEM
# When in ITEM mode, a player must have this item to catch a creature.
Cost Item: STICK
Cost Amount: 1
# When in VAULT mode, a player must have at least this amount of money.
Cost Vault: 10
# In these worlds, you cannot capture or release creatures.
Disabled Worlds: []
# Should eggs take the color of the creature they belong to?
Colored Eggs: true
# Should we hook into Towny
Towny Hook: false
# Are you using GriefPrevention?
GriefPrevention Hook: false
# Allow capturing creatures with melee
MeleeCapture: true
# Require projectile to contain key metadata.
Require Unique: false
# With '/mobcapture spawn', a projectile will be spawned with these values (only with Require Unique enabled).
Unique Display Name: '&6Mob Catcher'
Unique Lore:
  - '&3Shoot a mob with me!'